### ISSUE TITLE
Fingering position does not adapt to stems with beaming

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#105]
See unit test:
```

{[  
    \clef<"g2"> \key<0> \meter<"C"> \stemsUp \beamBegin:1 \beamBegin:2 
   \fingering<text="1", position="above">( e0/16) 
   \fingering<text="4", position="above">( e1/16)
  \fingering<text="1", position="above">( b0/16)
  \fingering<text="3", position="above">( g1/16)
 \beamEnd:2 \beamEnd:1  
 \beamBegin:1 \beamBegin:2 
 \fingering<text="4", position="above">( e/16)
  \fingering<text="1", position="above">( b/16)
 \fingering<text="2", position="above">( g/16)
 \fingering<text="3", position="above">( e2/16)
 \beamEnd:2 \beamEnd:1 
 \beamBegin:1 \beamBegin:2 
 \fingering<text="4", position="above">( b1/16)
 \fingering<text="5", position="above">( e2/16)
 \fingering<text="1", position="above">( g1/16)
 \fingering<text="2", position="above">( b/16)
 \beamEnd:2 \beamEnd:1 
 \beamBegin:1 \beamBegin:2 
 \fingering<text="1", position="above">(e/16) 
 \fingering<text="2", position="above">(g/16) 
 \fingering<text="3", position="above">( b0/16)
  \fingering<text="4", position="above">(e1/16) 
  \beamEnd:2 \beamEnd:1 
 ]
  }
```

Current rendering result - Note that it is also uneven for a beaming with slope 0 (last group):
![image](https://user-images.githubusercontent.com/3298204/71828589-e4390a00-30a2-11ea-9dd8-c7ea45d35222.png)

**Comment by dfober** [comment]
A bit tricky to solve! Actually this is due to the order of the `tellposition` call: fingering is called before beaming and thus adapts to a stem length which is then modified by beaming.
Different solutions could be considered: 
- the brute force: make a second pass of `tellposition` -> will likely result in a significant performance degradation since the entry point makes a lot of other tasks.
- sort the graphic elements so that `tellposition` is called with the correct order. But is there a correct order? Wouldn't there be circular dependencies? (I don't know)
- identify the context where a second pass is necessary and recall `tellposition` only for elements that need to be recomputed.
This last solution seems to me the most reasonable but may take some time to implement.

**Comment by dfober** [comment]
Fixed and pushed.
I've eventually implemented the brute force but limited to notes and fingering (it shouldn't significantly affect efficiency).

**Comment by arshiacont** [comment]
Works like a charm! We just brought xml2guido to the next level of beauty! ;) PR upcoming for LibMusicXML.
Many thanks.
