### ISSUE TITLE
About the guido library

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/guidolib#141]
Regarding the guido library, does it not support active line wrapping of subsections in xml?

**Comment by arshiacont** [comment]
Can you give an example of line wrapping of subsections in xml?

Note that Guido has actually nothing to do with MusicXML and XML! It appears that the LibMusicXML proposes a convertor from MusicXML format to Guido format.

There is the GuidoAR repo which comes with various tools such as transpositions, wrapping of sections etc that you can use in parallel: https://github.com/grame-cncm/guidoar

**Comment by zhwei8090** [comment]
I'm sorry, I have a problem with my expression. In fact, there are some differences between what I see on the score creation software and what I see after converting to guido. For example, the number of measures occupied by each line is inconsistent, and the width of each measure is inconsistent. , so that there are differences in the text and mark symbols that I need to display on the score making software, which greatly affects the beauty and efficiency of making scores

**Comment by zhwei8090** [comment]
@arshiacont We use the software MuseScore, and we have also tried Finale. There are also some compatibility problems. I don’t know how you solved it, or have any better suggestions.

**Comment by arshiacont** [comment]
@zhwei8090 so this a LibMusicXML issue so we should probably move this to the issue over there: https://github.com/grame-cncm/libmusicxml/issues 

The `xml2guido` in that library is _tuned_ for Finale output. This is only because other software, such as MuseScore or Sibelius do not encode music scores in the same way and we found that Finale's output is more consistent!!! In most cases, if you import from MuseScore to Finale, clean up and export; you'll get better result!

Also: Not _all_ elements in a music score encode to MusicXML! For example, pure graphical elements don't so you need sometimes to correct those.

In my experience, 95% of the times where Guido rendering is not right from MusicXML, it is related to the MusicXML or xml2guido! :)

**Comment by zhwei8090** [comment]
@arshiacont   Understood, thank you very much
