### ISSUE TITLE
How to space note proportional to rhythmic duration?

### ISSUE THREAD

**Issue by iomeone** [grame-cncm/guidolib#156]
Thanks for the great library! I just want to ask something about space.
LilyPond supports proportional notation, a type of horizontal spacing in which each note consumes an amount of horizontal space exactly equivalent to its rhythmic duration. 

[http://lilypond.org/doc/v2.19/Documentation/notation/proportional-notat…](http://lilypond.org/doc/v2.19/Documentation/notation/proportional-notation)

How can I achieve the same effect using guidolib?

**Comment by dfober** [comment]
Proportional notation is really poorly supported by the guido engine.
You can force proportional rendering using the engine settings (not available with the online editor but supported by the native application). It was an experimental attempt that should be revised: there are a lot of collisions, especially with signs that have no duration (key, meter etc.).
The problem seems simple to solve but complex to implement in the current state of the guido engine.
