### ISSUE TITLE
Mordent on a chord

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#16]
Rendering is aborted in Guido (all instances) if `noteFormat` is nested within `\acc` or `\stacc` or `\mordent` or similar as seen in this score excerpt: [SoloLine.txt](https://github.com/grame-cncm/guidolib/files/974063/SoloLine.txt)

Score source is Bartok's _Romanian Folk Dance N°3_ for violin. See 
[PDF rendered in another editor](https://github.com/grame-cncm/guidolib/files/974069/SoloLine.pdf) and [MusicXML Source](https://github.com/grame-cncm/guidolib/files/974074/SoloLineMusicXML.txt).

The score is rather simple and reduced to a minimal version to detect various nesting bugs.

**Suggestion:** Admin should probably enable file uploads with `gmn` and `xml` file extensions in this repository! :)

**Comment by dfober** [comment]
Could you provide a more simple example. The score is too large to be usable for debug. Actually and regarding any issue, you should isolate the problem with a minimal score i.e. a score where removing any element suppresses the issue. Generally, a few notes and tags are enough. When the problem is related to a line break, you can simulate it using a \newLine tag.

**Comment by arshiacont** [comment]
Here is [one small unit test](https://github.com/grame-cncm/guidolib/files/975869/nestingBug_mordentBug_gmn.txt).

Note that the `mordent` tag in staff one evades rendering of the note with noteformat. Whereas in Staff 2, we have the same thing _without_ the `mordent` tag.

**Comment by dfober** [comment]
ok, I see...
actually the minimal code is `\mord( { g#1/8, \noteFormat<"diamond">( c#2/8) })`
which is equivalent to `\mord( { g#1/8, c#2 })`
and it's completely legal and correct  (rendering included)
In fact, a mordent is specified using a chord (see https://github.com/grame-cncm/guidolib/blob/dev/doc/GUIDO_Additional_Specifications_1.3.8.pdf) but now, the problem is that you can't put a mordent on a chord without generating a syntax error since nested chords are not allowed...
There are two solutions to support what you want to do:
- modify the parser to support nested chords in the context of mordents, which is not trivial since the parser is completely agnostic and don't know anything about mordents
- change the mordent syntax
I think the later is simpler and should simplify mordents support. And since it's a recent addition, I guess introducing a syntactic change and incompatibility should not be too harmful.

**Comment by arshiacont** [comment]
Well detected!

I'm actually generating this from MusicXML and I had to adapt the `xml2guido` code with specific processing for all ornaments that take chords as input (see `xmlpart2guido::checkChordOrnaments`in LibMusicXML) which are _mordents_, _turns_ and also _trill_ to some extent. Curiously `\trem` gets a note-list. In that code, I am actually _generating_ the play behavior of `mordent` to comply with Guido syntax. 

One source of inspiration if you want to create a new syntax could be _MusicXML_: In MusicXML, these tags only include the visually rendered notes as their argument value and their _play_ behavior is determined by attributes. This way for example the `\mordent` tag includes only the notes to be visually rendered, and an attribute can determine whether it is inverted or not, etc.

**Comment by arshiacont** [comment]
As a side note, I should get the visual equivalence of my intended `\mord( { g#1/8, c#2 })`  using `{ g#1/8, \mord({ c#2/8, d}) }`. But the latter leads to an error... and I believe it _can_ happen in polyphonic contexts such as in piano scores.

**Comment by dfober** [comment]
solved with the version 1.6.5
actually all ornaments syntax (\trill \mordent \turn) has been revised: they are not specified with a chord any more, which allows to apply them to a chord. A parameter is used instead. See the samples in new-tags-v1.65.

**Comment by arshiacont** [comment]
Many thanks
