### ISSUE TITLE
Octavia on cross-staff can lead to destructor Crash

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#174]
The following reduced excerpt leads systematically to crash on `GuidoFreeGR` (if freed after rendering) and more specifically on `GRPositionTag::DeleteStaff(GRStaff*)`.

_Hint_: If you remove the two `\oct`, the crash disappears!

```
{[  (* meas. 1 *)  \clef<"g2"> \key<2> \meter<"C"> 
   \oct<1> \staff<2> \stemsUp \beamBegin:1 {f#2/8, f#3/8  } \staff<1> {f#3/8, f#4/8  } \staff<2> {e2/8, e3/8  } \staff<1> {e3/8, e4/8  } \beamEnd:1 \staff<2> \beamBegin:1 {c#2/8, c#3/8  } \staff<1> {c#3/8, c#4/8  } \staff<2> {\acc( a#1/8)
, \acc( a#2/8)} 
\oct<0> \staff<1> {a#2/8, \acc( a#3/8)} \beamEnd:1 ]
  }
```

**Comment by dfober** [comment]
I've been lucky with the previous crash bug since the solution was to remove useless associations. This is not the case here and it looks like a tricky case to solve. This kind of issue has been [identified years ago](https://github.com/grame-cncm/guidolib/blob/dev/src/engine/graphic/GRPositionTag.cpp#L85). Automatic memory management is the ultimate solution but that's a huge task. I'll see if I can find a quick solution.

**Comment by dfober** [comment]
In fact, the crash is caused by the fact that the 2 octavas are on different staffs. It's a slightly ambiguous case: an octava that starts on one staff and ends on another doesn't make much sense graphically. I think it should be possible to resolve this at the AR level.

**Comment by arshiacont** [comment]
Oh I see! Effectively the octave off here is not normal and does not make sense!! 
I will fix this in _xml2guido_!
If we can just avoid the engine crash in such cases it would be ideal.

**Comment by dfober** [comment]
Of course, I'll fix it. Zero crash is the goal.

**Comment by dfober** [comment]
the crash bug is solved but I have to fix the display

**Comment by dfober** [comment]
fixed, including incorrect rendering
