### ISSUE TITLE
NULL Map at ARStaff Initialization

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#33]
The newly `TagParameterMap::Add` method fills an uninitialized STL Map using the regular `key = value` of `operator[]` STL methods.

This is dangerous if the pair does not initially exists and can lead to run-time crash on several platforms. The problem is that the defined prototypes are not _default initialized_.

It is actually the case for ARM!

We should probably use STL `insert` method instead to avoid this.

See [this stackoverflow post](https://stackoverflow.com/questions/17172080/insert-vs-emplace-vs-operator-in-c-map) for details.

**Comment by arshiacont** [comment]
Update:

It seems that the problem comes from the fact that the _map_ argument in `void TagParameterMap::Add (const TagParameterMap& map)` is `NULL` initiated after GuidoParser through ARStaff init constructor, and causing a run-time crash on iOS.

Has something changed in the way we should parse a GMN score?!

**Comment by arshiacont** [comment]
OK So here is the problem I am encoutering. It has nothing to do with iOS or architecture but with recent changes to the `GuidoInit` in the new API:

The [new] static `gMaps` is being initialized in `GuidoInit` now. GuidoInit was useful before for Rendering but not necessarily for Parsing. Now you need to use it _also_ before parsing a GMN file.

- Isn't requiring `GuidoInit` (with font and GDevice init) overkill just for parsing a file?
- Looking at `TagParametersMaps`, the default values inside are actually related to AR stuff and not the GR stuff. Can't we keep the `gMaps` initialization outside this and automatically upon class creation? They don't seem to be device specific of any kind.

**Comment by dfober** [comment]
Sorry, I'm not very reactive (due to health problems).
I agree, GuidoInit just for parsing is a bit heavy however, creating an AR without conversion to GR seems a bit weird. Why do you need that? The advantage of a centralised maps initialisation is multiple:
- it guaranties a constant time for AR creation (vs. map initialisation on class creation)
- it makes the implementation far more easy (no need to modify all the AR classes, which is really tedious).
An intermediate solution could be to have a _light_ init API (called also by GuidoInit) that could initialise the parameters maps only.

**Comment by arshiacont** [comment]
@dfober : You are right! I changed the way we construct and initialize things! You can mark this issue as _invalid_ if possible.

And get well and thanks for your reactivity.
