### ISSUE TITLE
Enhancement: Add placement parameter for Fingering tag

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#62]
The `Fingering` tag in current GuidoLib is pretty useful but it will be even more useful if we could add a `Placement` parameter to put the fingering. Currently the tag accepts _dy_ and _dx_ parameters and the default position is _below_ the encompassed events.

While this works when the stem is pointing upwards, it would be impossible to calculate correct dy when the stem is pointing downwards.

Adding a `placement` or `position` parameter similar to Articulations in Guido will solve this problem.

**Comment by dfober** [comment]
Agree. but I won't have time until February.

**Comment by arshiacont** [comment]
No problem. Meanwhile, I imagine that you are going to overload Fingering with an existing class. If there is an example of this I can look at + pointers on which class to use, I can start looking and submit a Pull Request.
Happy new year! :)

**Comment by dfober** [comment]
Happy new year too !

Actually, adding a new parameter at AR level is easy. Currently, ARFingering is almost only a type derived from ARText (see src/engine/abstract/ARFingering.h).
- first step is to create  the fingering parameters in src/engine/abstract/TagParameterStrings.cpp / h (there none since it inherits only ARText parameters) and to handle the parameter in an implementation file (ARFingering.cpp doesn’t exist yet). There are many examples with other AR classes.
- next step is to handle the parameter at graphic level and that’s likely a bit more complex. There is actually no GRFingering class, fingering is handle by the GRText class and maybe it’s worth to derive GRText to a new GRFingering class. 
You can have a look at similar classes to see how to compute contextual information for automatic placement. 
The main question (maybe easy to solve with the current literature on the subject e.g. Gould) is what is a good automatic placement for fingering? is it the one illustrated in gmn-examples/tags/fingering.gmn? 

Otherwise I’m in favour of ‘position’ for the tag name (already widely used) that could take the following values:
- notehead (default) : the current position, anchored to the note head
- above : on top of the note bounding box (should take care of articulations etc…)
- below : below the note bounding box (should take care of articulations etc…)
- auto   : ?

let me know what you think

**Comment by dfober** [comment]
that's done ! Examples of the new attributes are available from `gmn-examples/new-tags-v1.66`
Any comment or additional suggestion ?

**Comment by arshiacont** [comment]
Wow! Thanks Dominique.. I'll have a look on Monday when I'm back in town! :) 

I just added a request for Pedal tag.. 

and am asking our copyist what would be improvements they can't live without.. Will let you know :)
