### ISSUE TITLE
Slur slope explosion

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#66]
on Measure 1 of this GMN example:

`{[  
   (* meas. 1 *)  \clef<"g2"> \stemsUp \slurBegin:1<curve="down"> \beamBegin:1 e/16 d#/16 c#/16 d#/16 e/16 f#/16 \beamEnd:1 \beamBegin:1 e/16 d#/16 c#/16 d#/16 e/16 f#/16 \beamEnd:1 \slurEnd:1 \bar 
   (* meas. 2 *)  \slurBegin:1<curve="up"> \beamBegin:1 e/16 d#/16 e/16 f#/16 g#/16 \dimBegin<dy=-2.8hs> a/16 \beamEnd:1 \stemsDown \beamBegin:1 b/16 c#2/16 d#/16 e/16 f#/16 g#/16 \beamEnd:1 \slurEnd:1 \dimEnd ]
  }`

Rendered in Guido: 
![screenshot 2019-02-14 at 17 42 04](https://user-images.githubusercontent.com/3298204/52802269-e441ad00-307f-11e9-8e83-a270fe9071df.png)

Note that this phenomenon usually makes the slur in question collide with the next System.

**Comment by arshiacont** [comment]
In case you are calculating the base Slur parameters using the `curve` tagParameter, I'd be curious to take a look there and see how `h` are explodes.. We actually see this phenomenon on various places

**Comment by dfober** [comment]
this is actually computed in GRSlur.cpp : `GRSlur::automaticControlPoints`
The rationale is to compute 3 points that form an isosceles triangle. The task is easy for the anchor points (leftmost and rightmost, computed elsewhere). The middle point is adjusted according to the bounding boxes of the enclosed notes and results from start and end slopes computations. 
It's quite tricky to modify the algorithm without breaking the rendering (that works pretty well in most situations).  I think one of the issues is the symmetry of the design : both slopes (start and end) are forced to the same value while it might sometimes be more elegant to have an asymmetric slur.
In the above example, the sharp on the second note enforces a steep slope from the beginning (just remove it to see). One solution could be to move the left anchor point a bit lower (which could preserve the symmetry of the design). But for the time being, the problem is to detect this kind of situation and to identify the possible anchor point to move...

**Comment by dfober** [comment]
fixed (but still room for improvements)
